@startuml

component core{
package jobblett.core
}

component fxui{
package jobblett.ui
}

component json{
package jobblett.json
}

component google.guava{
}

component javafx{
	component fxml{
	}
}
component jackson{
}

component restapi{
package jobblett.restapi
}

component restserver{
package jobblett.restserver
}


component integrationstest{
package jobblett.integrationstest
}


jobblett.ui ..>fxml
jobblett.core ..> google.guava
jobblett.ui ..> jobblett.core
jobblett.json ..> jackson
jobblett.ui ..> jobblett.json
jobblett.json ..> jobblett.core

jobblett.restserver ..> jobblett.core
jobblett.restserver ..> jobblett.json
jobblett.restserver ..> jobblett.restapi


component jersey {
}

component grizzly2 {
}

restserver ..> jersey
restserver ..> grizzly2
jobblett.integrationstest ..> jobblett.ui
jobblett.integrationstest ..> jobblett.restserver




@enduml
